blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/DaWeba02/OpenANV/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
